### ISSUE TITLE
Bug in broken refs code

### ISSUE THREAD

**Issue by tomduck** [tomduck/pandoc-xnos#1]
The following markdown causes pandoc-fignos to crash:

~~~ .markdown
["This"], crashes fignos.

["This"]: https://google.com/
~~~

The problem occurs with the `["This"],` portion.  If the quotes or comma are dropped, then everything is fine.  Single quotes also cause a crash.

Here is the session:

~~~ .bash
$ pandoc-1.17.2 demo2.md --filter pandoc-fignos -o out/demo2.pdf
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/bin/pandoc-fignos", line 9, in <module>
    load_entry_point('pandoc-fignos==0.16', 'console_scripts', 'pandoc-fignos')()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandoc_fignos-0.16-py3.4.egg/pandoc_fignos.py", line 368, in main
    # Insert supporting TeX
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandoc_fignos-0.16-py3.4.egg/pandoc_fignos.py", line 366, in <lambda>
    
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandocfilters-1.3.0-py3.4.egg/pandocfilters.py", line 34, in walk
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandocfilters-1.3.0-py3.4.egg/pandocfilters.py", line 25, in walk
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandoc_xnos-0.4.1-py3.4.egg/pandocxnos/core.py", line 474, in repair_refs
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandoc_xnos-0.4.1-py3.4.egg/pandocxnos/core.py", line 119, in wrapper
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandoc_xnos-0.4.1-py3.4.egg/pandocxnos/core.py", line 428, in _repair_refs
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/pandoc_xnos-0.4.1-py3.4.egg/pandocxnos/core.py", line 413, in _is_broken_ref
TypeError: can only concatenate list (not "str") to list
pandoc-1.17.2: Error running filter pandoc-fignos
Filter returned error status 1
~~~

**Comment by tomduck** [comment]
This is fixed in the `nextrelease` branch, which will become pandoc-xnos 0.5.
