### ISSUE TITLE
TypeError: write() argument 1 must be unicode, not str

### ISSUE THREAD

**Issue by eddyc** [tomduck/pandoc-xnos#19]
Hi, I'm having trouble running pandoc-xnos on macOs Big Sur with Python 2.7. I'm getting the following error:
```
[INFO] Running filter pandoc-shortcaption
[INFO] Completed filter pandoc-shortcaption in 128 ms
[INFO] Running filter pandoc-xnos
Traceback (most recent call last):
  File "/Users/eddyc/Library/Python/2.7/bin/pandoc-xnos", line 8, in <module>
    sys.exit(main())
  File "/Users/eddyc/Library/Python/2.7/lib/python/site-packages/pandocxnos/main.py", line 38, in main
    m.main(stdin, stdout)
  File "/Users/eddyc/Library/Python/2.7/lib/python/site-packages/pandoc_fignos.py", line 663, in main
    json.dump(doc, stdout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 190, in dump
    fp.write(chunk)
TypeError: write() argument 1 must be unicode, not str
Error running filter pandoc-xnos:
Filter returned error status 1
```

**Comment by eddyc** [comment]
Seems to be a Python 2.7 issue, works with 3.8, closing

**Comment by tomduck** [comment]
Hi, @eddyc.  Thanks for submitting this issue.  I am wondering if you could provide some markdown that exposes this error?  Or does this happen with any markdown?  Python 2.7 is one of my targets, and my python 2.7 tests on MacOS Catalina pass.  Thanks, Tom.
